### ISSUE TITLE
Використання простих змінних в Ruby

### ISSUE THREAD

**Issue by dmytro** [dmytro/git-training#12]
# Тема

## Використання простих змінних в Ruby

- Присвоєння значення змінній в Ruby і в `shell` (`bash`)
- Використання змінних в Ruby і в `shell`
  - різниця використання змінних в Ruby

# Домашнє завдання

- Назви змінних
  - Які з наведених далі назв можуть використовуватися як назви змінних у Рубі? 
  - Які не можна використовувати як змінні? Пояснити чому?

  Назви: `my_name`, `name`, `Name`, `my variable`, `number`, `Very-Big-Number`, `Very_Big_Number`, `42`, `42_is_a_magic_number`, `forty_two`
   

- Написати програму на Ruby, яка демонструє використання змінних різних типів: 
  - цілих чисел, 
  - десяткових дробів, 
  - текстових рядків

- Написати програму на Ruby, яка демонструє маніпуляції зі змінними різних типів:
  - додавання і віднімання цілих і дробових змінних;
  - об'єднання ("склеювання" або "конкатенація") текстових змінних

## Матеріал до теми

- [Вікіпідручник: Змінні](https://goo.gl/PFTFUm)
- [Ruby для новачків: змінні, типи даних та файли](https://php-academy.kiev.ua/uk/blog/ruby-for-newbies-variables-datatypes-and-files)

## Додатковий матеріал для самостійної роботи

- https://goo.gl/jHti7v - розібратися що означає "duck typing" ("качина типізація", або латентна типізація) ?
- різні типи даних - https://www.sites.google.com/site/da3215mulik/ruby/urok-3

---

### Як виконувати домашнє завдання
- Весь опис, і текст програми подати як Github pull request.
- Відповіді мають бути записані в окремому файлі.
- В PR включається файл програми і файл README.md.
- Обидва файли включені в піддиректорію і гілку git відповідну до теми.
- Відповіді надавати українською мовою.

**Comment by dmytro** [comment]
# Домашнє завдання - продовження

1. Розуміння і використання команд:
- `git status`
- `git log`
-  `git checkout`
- `git push`
- `git pull`
- `git merge`

2. Закінчити попереднє завдання

**Comment by pavloolenchyk** [comment]
git status -  показує стан робочої директорії і які файли були / не були видані на коміт.
git log - список комітів з кожним повідомленням що відповідає за коммітомю
git checkout - переходить між гілками
git push - відсилає локальні файли на віддалену репозиторій 
git pull - встановлює файли із віддаленого репо у локальний репо
git merge - вставляє зміни із названих коммітів у поточну гілку
