### ISSUE TITLE
Функції і методи в Рубі

### ISSUE THREAD

**Issue by dmytro** [dmytro/git-training#15]
# Функції і методи

- Що таке методи?
- Використання методів
- Аргументи методів
- Визначення методів — як створити свій власний метод

# Домашнє завдання
- Самостійно почитати і спробувати розібратися з методами Рубі

## Матеріал до теми

- https://php-academy.kiev.ua/uk/blog/ruby-for-newbies-operators-and-their-methods
- [Вікіпідручник: Методи](https://uk.wikibooks.org/wiki/Ruby#%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D0%B8)
- Розділ Methods в [Why's (Poignant) Guide to Ruby](http://poignant.guide/book/chapter-3.html)

Рекомендую для прочитання весь розділ A Quick (and Hopefully Painless) Ride Through Ruby (with Cartoon Foxes) в [Why's (Poignant) Guide to Ruby](http://poignant.guide/book/chapter-3.html). Це — найбільш відомий підручник по Рубі, написаний в прекрасному стилі, дуже легкий для читання.

## Додатковий матеріал для самостійної роботи

- N/A

@pavloolenchyk 
---

### Як виконувати домашнє завдання
- Весь опис, і текст програми подати як Github pull request.
- Відповіді мають бути записані в окремому файлі.
- В PR включається файл програми і файл README.md.
- Обидва файли включені в піддиректорію і гілку git відповідну до теми.
- Відповіді надавати українською мовою.

**Comment by dmytro** [comment]
# Продовження домашнього завдання

Розібратися самостійно як створювати методи в Рубі. Як створюються методи з параметрами.

Додатковий ресурс:

- https://www.ruby-lang.org/en/documentation/quickstart/2/

## Завдання

1. Написати метод `hi` який би робив наступне:

```
[18] pry(main)> hi "Dmytro"
Hello Dmytro=> nil
[19] pry(main)> hi "Pavlo"
Hello Pavlo=> nil
[20] pry(main)>
```

2. Написати метод `introduce` який би робив таке:
```
[23] pry(main)> introduce "Pavlo", "Dmytro"
Hi Pavlo. This is my friend Dmytro=> nil
[24] pry(main)>
```

Завдання виконати в `irb` і долучити знімок екрану виконання обох методів.

**Comment by pavloolenchyk** [comment]
![Screen Shot 2019-04-21 at 10 05 09](https://user-images.githubusercontent.com/34408189/56464104-18896f00-641d-11e9-97e0-6dec7a5fc582.png)

**Comment by pavloolenchyk** [comment]
![Screen Shot 2019-04-21 at 10 08 28](https://user-images.githubusercontent.com/34408189/56464121-71590780-641d-11e9-8c0b-522083eaaab6.png)

**Comment by dmytro** [comment]
Well done
