### ISSUE TITLE
Змінні класу, конструктори

### ISSUE THREAD

**Issue by dmytro** [dmytro/git-training#20]
# Змінні класу в Рубі
## Класи

Попередні теми:  
- локальні змінна належить методу і її значення відоме тільки всередині одного конкретного метода. 
- змінна екземпляра належить об'єкту (або екземпляру) і її значення відому в межах одного конкретного об'єкта. Прикладом змінної екземпляра може бути ім'я людини в класі Human.

Змінні класу — це змінні, які належать всьому класу. Прикладом змінної класу може бути: населення Земної кулі у класі `Human`, або масив усіх книжок, у бібліотеці. 

Назви змінної класу починаються з двох знаків `@@`: Наприклад: `@@population`.

# Домашнє завдання
Доповнити конструктори з попереднього завдання так, щоб: 
- при створенні нового екземпляра в класах `Mammal`, `Primate`, `Human` кількість населення збільшувалося і 
- доповнити класи методами (`getter`), який би повертав розмір класу на даний момент,

## Матеріал до теми

- Розділ `Ruby Class Variables` в https://www.tutorialspoint.com/ruby/ruby_variables.htm
- https://maximomussini.com/posts/ruby-class-variables/
- http://www.railstips.org/blog/archives/2006/11/18/class-and-instance-variables-in-ruby/

---

### Як виконувати домашнє завдання
- Весь опис, і текст програми подати як Github pull request.
- Відповіді мають бути записані в окремому файлі.
- В PR включається файл програми і файл README.md.
- Обидва файли включені в піддиректорію і гілку git відповідну до теми.
- Відповіді надавати українською мовою.

**Comment by pavloolenchyk** [comment]
Commit 53144050efce80ee4dbbba622ac9c97f23e7a306

**Comment by pavloolenchyk** [comment]
2af9275

**Comment by dmytro** [comment]
# Продовження домашнього завдання

Дата: 20 жовтня 2019

## Тема: конструктор і доступ до змінних екземпляру. 

### Завдання
- ще раз уважно пройтися по зробленому в PR #21 
- розглянути і добре зрозуміти клас `Mammal` в файлі `dolphin.rb`
- повторити **самостійно** те ж саме, але з іншим класом (на власний вибір)

**Примітка**: для виконання завдання створити нову гілку (branch) і новий PR.

@pavloolenchyk
