### ISSUE TITLE
Структури управління

### ISSUE THREAD

**Issue by dmytro** [dmytro/git-training#32]
# Cтруктури управління
 *(англ. control structures) - цикли і умовні переходи*

## Огляд теми

- Ознайомлення з різними типами циклів у Рубі
  - `for ... in ...`
  - `.each do |x|`
  - ` while ... do`
  - `until ... do`
- Логічні переходи
  - `if ... elsif ... else ... end` — прямий логічний перехід. Перевіряє умову на правдивість (`true`)
  - `case ... when`
  - потрійний оператор (англ.: ternary operator) логічний вираз 
    `<condition> ? <if_true> : <if_false> `
- Зворотні логічні вирази
  - `unless ... end` — перевіряють на неправдивість (`false`)
    - `unless ... else ... end` — підваріант, через складність логіки використовується рідко
- Однорядкові логічні вирази: спочатку йде код для виконання, в кінці умова.
  - `<expr> if <cond>`
  - `<expr> unless <cond>`
---
## Робота в класі
Дата: 2020-02-09

- Розглянули цикли типу `each` та `for ... in`
  - відмінності циклу `for ... in ` від циклу `for` з інкрементом
- Розглянули типи логічного переходу
  - `if ... end` - найпростіший варіант
  - `if ... else ... end` 
- Методи `Fixnum#even?`, `Fixnum#odd?`

# Домашнє завдання
**Дата: 2020-02-09**

**Обов'язково**: Прочитати внизу сторінки розділ "Як виконувати домашнє завдання" і притримуватися його при виконанні завдань.

- [x] Оформити роботу в класі як Pull Request

Всі наступні завдання виконувати, як окремі PR, кожен в своїй окремий гілці (_branch_).

### Матеріал до теми

Для освоєння матеріалу використовувати цей підручник: [The Beginner's Guide to Ruby If & Else Statements ](https://www.rubyguides.com/ruby-tutorial/ruby-if-else/) 

- Розділ *"If Construct in One Line"* — однорядкові логічні переходи.
- Зворотні логічні вирази `unless ... do ... end` (розділ *"Ruby Unless Statement"* там же)

**Завдання**
- [x] Написати функцію, яка приймає, як аргумент масив натуральних чисел і друкує на `STDOUT` всі числа у вигляді `N is even` чи `N is odd`. Користуватися одночасно (1) зворотним та (20 однорядковим логічним переходом  ( тобто `<expression> unless <condition>` ). 

## Завдання №2

З того ж самого підручника, що використовувався в попередньому завданні проробити розділ *"Is There an Alternative?"* про потрійний оператор (ternary operator).

**Завдання** 
- [x] Написати функцію, аналогічну функції в попередньому завданні, але при цьому користуватися потрійним оператором. 

---
## Матеріали до теми

- [The Beginner's Guide to Ruby If & Else Statements ](https://www.rubyguides.com/ruby-tutorial/ruby-if-else/) 
- [Ruby Loops: Repeating Something Many Times](https://www.rubyguides.com/ruby-tutorial/loops/)

## Додаткові матеріали

- [Geeks For Geeks | Decision Making](https://www.geeksforgeeks.org/ruby-decision-making-if-if-else-if-else-if-ternary-set-1/)
---

### Як виконувати домашнє завдання

Користуватися контрольними списками (checklists) – виконані завдання відмічати галочкою. Також звіритися виконання домашнього завдання зі списком нижче. 

- [ ] Кожне домашнє завдання виконувати в окремій гілці (branch).
- [ ] Весь опис, і текст програми подати як Github pull request.
- [ ] Відповіді мають бути записані в окремому файлі.
- [ ] В PR включається файл програми і файл README.md.
- [ ] Обидва файли включені в піддиректорію і гілку git відповідну до теми.
- [ ] Відповіді надавати українською мовою.

**Comment by pavloolenchyk** [comment]
Першу частину зроблено без проблем, а от з потрійним оператором проблема є.
![Screen Shot 2020-02-29 at 14 37 56](https://user-images.githubusercontent.com/34408189/75601745-8bfe1180-5b01-11ea-84b0-6e2e9ee6bec2.png)
![Screen Shot 2020-02-29 at 14 38 44](https://user-images.githubusercontent.com/34408189/75601747-8f919880-5b01-11ea-806b-6ab2838fc778.png)
Допоможіть!
