### ISSUE TITLE
5. Тема markdown

### ISSUE THREAD

**Issue by dmytro** [dmytro/git-training#6]
- Markup мови (Markup Languages)
  - HTML
  - XML 
  - SGML 
- `markDOWN`

# Приклади
### Заголовок 3

- bullet point
  - bullet point 2

`фіксована ширина`

```
блок коду
   -- 
    форматування зберігається
```

**Comment by dmytro** [comment]
# Завдання в класі

- Скопіювати відповіді на попереднє завдання в коментар до цієї теми
- Відформатувати використовуючи `markdown`

**Comment by pavloolenchyk** [comment]
# Завдання в класі
Код, який потрібен, щоб написати, відіслати, і взяти із GitHub.
```
cd training
vi readme.txt
git status
git add readme.txt
git status
git commit
git log
git diff
git push
cd ../training2
git pull
```

**Comment by dmytro** [comment]
## Приклад номер коміта

Просто вставляється посилання на коміт d162bbb23c8dda13176f645a0338a92e03ddc53c

**Comment by dmytro** [comment]
# Домашнє завдання

Написати *форматований* опис тих команд `Markdown`, які ми вивчили на уроці:
- заголовки різних рівнів
- булліти
- блоки коду і фіксовані шрифти
- посилання на комміти

**Comment by pavloolenchyk** [comment]
# Заголовок 1(через 1 #)
## Заголовок 2 (через 2 #)
### Заголовок 3 (через 3 #)
#### Заголовок 4 (через 4 #)
##### Заголовок 5 (через 5 #)
###### Заголовок 6 (через 6 #)
макс 6 заголовків
* Item (через *)
- Item (через -)
булліти через 2 символа, * і - .
`code` (через `)
`фіксований шрифт` (через `)
код або фіксований шрифт через ` (бектік)
d162bbb23c8dda13176f645a0338a92e03ddc53c (через копі-пейст)
із сторінки коммітів
@dmytro (через @)
mention використовуєтся щоб когось покликати до issue.

**Comment by dmytro** [comment]
### Зауваження до домашнього завдання
1. Якщо в завданні вказано *опис*, то потрібно написати саме *опис* тих, команд, які використовуються. Більш розширений, ніж зараз. 
2. Приклад із задником (`backtick`) не працює так, як потрібно (див. малюнок нижче — виділене червоним). Тобто, його якось потрібно ізолювати (escape), щоб показувався саме символ задника, і не спотворювались інші символи. **Завдання на самостійну роботу**: знайти як ізолювати символ задника.

![image](https://user-images.githubusercontent.com/81929/36955751-b7614eda-206d-11e8-8640-e088d156bbe7.png)

**Comment by pavloolenchyk** [comment]
Заголовок 1(через 1 #)
Заголовок 2 (через 2 #)
Заголовок 3 (через 3 #)
Заголовок 4 (через 4 #)
Заголовок 5 (через 5 #)
Заголовок 6 (через 6 #)
Заголовки викориристовуются, щоб показати головну ідею текста, або щоб привернути увагу до вказанної строчки тексту, щоб дати зрозуміти що це - тема, про яку буде іти мова. Заголовків у маркдауні є шість, і їх можна застосувати дякуючи допомозі hash (#), і щоб не дати посилання на іншу проблему, потрібно додати один пробіл після хеша.
Item (через *)
Item (через -)
булліти через 2 символа, * і - , якщо потрібно кілька штук написати як список.
`code`
`фіксований шрифт`
код або фіксований шрифт через ` (бектік) щоб покрило сирім (можна використати щоб привернути увагу до виділенного тексту).
(як ізолювати? не зрозумів я як оце зробити).
d162bbb (через копі-пейст)
із сторінки коммітів
@dmytro (через @)
mention використовуєтся щоб когось покликати до issue.

**Comment by dmytro** [comment]
Добре, молодець. Гарні описи. Залишилося ще трошки, ще не закінчене завдання для самостійної роботи. 

*Запитаня №2 з попереднього коментаря*: як ізолювати символ задника (`)? Наприклад, як  написати показане на знімку нижче:

![image](https://user-images.githubusercontent.com/81929/37561228-cd149a4c-2a8c-11e8-879c-91f45613ed13.png)

**Comment by dmytro** [comment]
Відповідь – невірна. Не закривай, будь ласка, поки не знайдеш правильну відповідь. Всі свої відповіді обов'язково перевіряй.

**Comment by pavloolenchyk** [comment]
Щоб ізолювати символ задника, потрібно використати один із двух способів. 
Перший спосіб - використати два символів задника перед і після тексту.
Приклад:

`` текст` ``

Другий спосіб - використати чотири пробіла перед текстом.
Приклад:

    текст`

І це все.

**Comment by pavloolenchyk** [comment]
Правильна відповідь - backslash.
\`
