### ISSUE TITLE
6. Using SSH keys

### ISSUE THREAD

**Issue by dmytro** [dmytro/git-training#9]
# Використання SSH ключів

## План уроку
- Що таке командна оболонка?
- Історія: віддалена командна оболонка `rsh`
- `ssh` — безпечна заміна для `rsh`
  - Весь обмін даними між комп'ютерами закодовано (encrypted). Для кодування використовуються тимчасові ключі, які створюються двома комп'ютерами тільки на час сеансу зв'язку;
  - Користувачі можуть з'єднуватися до віддалених комп'ютерів або з використанням імені/паролю (менш безпечно) або за допомогою криптографічних ключів;
- генерування ключів для  `ssh`, команда `ssh-keygen`
  - приватний і публічний ключі `~/.ssh/id_rsa`, `~/.ssh/id_rsa.pub`
  - завантаження публічного ключа в Github

**Comment by dmytro** [comment]
## Домашнє завдання

Під час уроку ми згенерували пару ключів, який складається з двох файлів: `~/.ssh/id_rsa` і `~/.ssh/id_rsa.pub`. 

1. Розібратися, куди, як і який файл треба завантажити в Github, щоб можна було виконувати віддалені `git` команди (`pull`, `push`) без використання пароля.
2. Підтвердити, ключ працює: створити невеликий коміт і зробити `push` **БЕЗ** викоритання пароля. 

*N.B.:* Бажано надати знімок екрана виконання команд.

**Comment by pavloolenchyk** [comment]
Public SSH key added to GitHub by pbcopy.
Passphrase created.
Added key to the ssh-agent.
Commit made.
git push done without needing the password.
![screen shot 2018-10-27 at 21 57 21](https://user-images.githubusercontent.com/34408189/47604340-550e7c00-da33-11e8-8e28-3f73cbd794f5.png)
Hopefully this works.
6e2687081689f81267ef647be1a0f796ff350acd

**Comment by dmytro** [comment]
Дякую, молодець @pavloolenchyk
